Warn snap confinement issues when program errors
This patch implements checks and warnings when the user run the snap
without connecting to the essential/optional confinement interfaces.

It will only be triggered if the program errors, and can be disabled via
setting the `disable-snap-confinement-warnings` snap configuration
option.

Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

diff --git a/snap/local/launchers/universal-update-utility-launch b/snap/local/launchers/universal-update-utility-launch
--- a/snap/local/launchers/universal-update-utility-launch
+++ b/snap/local/launchers/universal-update-utility-launch
@@ -3,6 +3,9 @@
 # environment changes to make the snap work here.  You may also insert
 # security confinement/deprecation/obsoletion notice of the snap here.
 
+# lint: The use of backticks in the printf messages is intended
+# shellcheck disable=SC2016
+
 set \
     -o errexit \
     -o errtrace \
@@ -11,5 +14,51 @@ set \
 
 #export IMPORTANT_ENVIRONMENT_VARIABLE=value
 
-# Finally run the next part of the command chain
-exec "${@}"
+# Run the command, if fails, check and present security confinement
+# warnings to the user
+if ! "${@}" \
+    && test "$(snapctl get disable-snap-confinement-warnings)" != true; then
+    snap_confinement_warning_triggered=false
+    if ! snapctl is-connected home; then
+        snap_confinement_warning_triggered=true
+        printf \
+            "Warning: It appears that the %s snap isn't connected to the \`home\` interface, accessing files under your home directory will not be possible.\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+        printf \
+            "To fix this problem run the following command as root:\n\n    snap connect %s:home\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+    fi
+
+    if ! snapctl is-connected raw-usb; then
+        snap_confinement_warning_triggered=true
+        printf \
+            "Warning: It appears that the %s snap isn't connected to the \`raw-usb\` interface, direct-access of USB devices will not be possible.\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+        printf \
+            "To fix this problem run the following command as root:\n\n    snap connect %s:raw-usb\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+    fi
+
+    if ! snapctl is-connected removable-media; then
+        snap_confinement_warning_triggered=true
+        printf \
+            "Warning: It appears that the %s snap isn't connected to the \`removable-media\` interface, accessing files under /media and /mnt directory will not be possible.\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+        printf \
+            "To fix this problem run the following command as root:\n\n    snap connect %s:removable-media\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+    fi
+
+    if test "${snap_confinement_warning_triggered}" == true; then
+        printf \
+            "To disable these warnings, run the following command as root:\n\n    snap set %s disable-snap-confinement-warnings=true\n\n" \
+            "${SNAP_NAME}" \
+            1>&2
+    fi
+fi
